### ISSUE TITLE
Verify scikit-learn sample works in Python 3.5 

### ISSUE THREAD

**Issue by gogasca** [GoogleCloudPlatform/cloudml-samples#320]
https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/sklearn

Internal reference: b/120086448

**Comment by nnegrey** [comment]
@gogasca @alecglassford @happyhuman 
Any updates on this?
Please take a look.

**Comment by nnegrey** [comment]
Ping

**Comment by happyhuman** [comment]
I tested it with 3.5.0 first. Jupyter does not run with that version of Python due to some Type error. I then switched to use 3.5.4. Jupyter ran fine.

Then, I started with https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/notebooks/scikit-learn/Training%20with%20scikit-learn%20in%20CMLE.ipynb and I got an error:

ERROR	2019-06-20 13:23:39 -0700	service		The replica master 0 exited with a non-zero status of 1. 
ERROR	2019-06-20 13:23:39 -0700	service		Traceback (most recent call last):
ERROR	2019-06-20 13:23:39 -0700	service		  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
ERROR	2019-06-20 13:23:39 -0700	service		    "__main__", mod_spec)
ERROR	2019-06-20 13:23:39 -0700	service		  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
ERROR	2019-06-20 13:23:39 -0700	service		    exec(code, run_globals)
ERROR	2019-06-20 13:23:39 -0700	service		  File "/root/.local/lib/python3.5/site-packages/census_training/train.py", line 154, in <module>
ERROR	2019-06-20 13:23:39 -0700	service		    bucket = storage.Client().bucket(BUCKET_NAME)
ERROR	2019-06-20 13:23:39 -0700	service		  File "/usr/local/lib/python3.5/dist-packages/google/cloud/storage/client.py", line 141, in bucket
ERROR	2019-06-20 13:23:39 -0700	service		    return Bucket(client=self, name=bucket_name, user_project=user_project)
ERROR	2019-06-20 13:23:39 -0700	service		  File "/usr/local/lib/python3.5/dist-packages/google/cloud/storage/bucket.py", line 139, in __init__
ERROR	2019-06-20 13:23:39 -0700	service		    name = _validate_name(name)
ERROR	2019-06-20 13:23:39 -0700	service		  File "/usr/local/lib/python3.5/dist-packages/google/cloud/storage/_helpers.py", line 39, in _validate_name
ERROR	2019-06-20 13:23:39 -0700	service		    'Bucket names must start and end with a number or letter.')
ERROR	2019-06-20 13:23:39 -0700	service		ValueError: Bucket names must start and end with a number or letter.
ERROR	2019-06-20 13:23:39 -0700	service		


I verified that the bucket exists and it is accessible to the code. I doubt that it is a python 3.5.4 issue, but it needs be investigated further.

**Comment by happyhuman** [comment]
The sklearn notebooks run with Python 3.5.4. Because the codes are in notebooks, I was unable to test them with Python 3.5.0.
