### ISSUE TITLE
Why is the output layer a value of 25?

### ISSUE THREAD

**Issue by ericsheetz** [GoogleCloudPlatform/cloudml-samples#46]
As this is a classification problem with only two classes I would expect the output layer to only have 2 neurons.

Judging by the hidden layers of [100, 70, 50, 25] it looks like the output layer is 25.

**Comment by elibixby** [comment]
Output layer is always `num_classes`, the final hidden layer is simply the size of the input to the output layer. Traditionally the output layer is not considered one of the "hidden layers" (nor is the input layer, which in this case is `sum(embedding_size * len(categorical_columns) + len(continuous columns))` ), and would not be considered a hyperparameter for the purpose of tuning either since it's a fundamental part of the data schema, so it is not included in that list.
